[project]
name = "jupyter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.29.5",
    "open3d>=0.19.0",
    "scikit-learn>=1.6.1",
]

[project.optional-dependencies]
mac = [

]
